# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notiky < Formula
  desc "Notiky CLI — local agent runtime and management tool for the Notiky platform"
  homepage "https://github.com/notiky/notiky-cli"
  version "0.1.25"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/notiky/notiky-cli/releases/download/v0.1.25/notiky_darwin_amd64.tar.gz"
      sha256 "ca9635715942f3790f1998d419cdf929fe7c6253269a6632cdd4583f22b3f52a"

      define_method(:install) do
        bin.install "notiky"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/notiky/notiky-cli/releases/download/v0.1.25/notiky_darwin_arm64.tar.gz"
      sha256 "a95d798ac5cf75c8d1abc239fd4cd254bcdb99ac37c0b3929bd750c12f840b16"

      define_method(:install) do
        bin.install "notiky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/notiky/notiky-cli/releases/download/v0.1.25/notiky_linux_amd64.tar.gz"
      sha256 "a300ba7eb1859b1da86451daa9f3bf8476297f4b4313d9a8d5a31e9e1cdc4e42"
      define_method(:install) do
        bin.install "notiky"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notiky/notiky-cli/releases/download/v0.1.25/notiky_linux_arm64.tar.gz"
      sha256 "7d9ea9f008c9785fbd75c4f764c767d2c2534a3faf1bdd8fb0389a8bb1021422"
      define_method(:install) do
        bin.install "notiky"
      end
    end
  end

  test do
    system "#{bin}/notiky", "version"
  end
end
