# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notiky < Formula
  desc "Notiky CLI — local agent runtime and management tool for the Notiky platform"
  homepage "https://github.com/notiky/notiky-cli"
  version "0.1.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/notiky/notiky-cli/releases/download/v0.1.10/notiky_darwin_amd64.tar.gz"
      sha256 "aeb173901cbca744a3a23ea8c0d4b309f6820ef588460cd19013d6bb744b6b78"

      define_method(:install) do
        bin.install "notiky"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/notiky/notiky-cli/releases/download/v0.1.10/notiky_darwin_arm64.tar.gz"
      sha256 "cba9f5c59cef835a56f8e453ea81dd4123512982634e198275c6b69d9e1af5d9"

      define_method(:install) do
        bin.install "notiky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/notiky/notiky-cli/releases/download/v0.1.10/notiky_linux_amd64.tar.gz"
      sha256 "0e798418d30d69b16ff6aa3add77bb657dc555427f098ba079ee92cb93d8c36d"
      define_method(:install) do
        bin.install "notiky"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notiky/notiky-cli/releases/download/v0.1.10/notiky_linux_arm64.tar.gz"
      sha256 "5a67f658ad9ccdd7eaec8c510c44f23e917ad8d2b32e6622ee83c46dab438726"
      define_method(:install) do
        bin.install "notiky"
      end
    end
  end

  test do
    system "#{bin}/notiky", "version"
  end
end
